# Generated by Django 4.2.5 on 2023-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Comunidad USM', 'Comunidad USM'), ('Estudiante', 'Estudiante'), ('Profesor', 'Profesor'), ('Jefe de Carrera', 'Jefe de Carrera')], max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('Titulo', models.CharField(max_length=55)),
                ('Descripcion', models.CharField(max_length=105)),
                ('Tipo', models.CharField(choices=[('V', 'Vacaciones'), ('F', 'Feriado'), ('S_A', 'Suspension de actividades'), ('S_A_PM', 'Suspension de actividades (PM)'), ('P', 'Periodo Lectivo'), ('S_E', 'Suspension de evaluaciones'), ('C', 'Ceremonia'), ('E', 'EDDA'), ('A', 'Ayudantias'), ('H', 'Hito Academico'), ('S', 'Secretaria Academica'), ('Q', 'QAI')], max_length=30)),
                ('Segmento', models.ManyToManyField(related_name='eventos', to='core.segmento')),
            ],
        ),
    ]
