# Generated by Django 4.2.5 on 2023-11-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Tipo',
            field=models.CharField(choices=[('V', 'Vacaciones'), ('F', 'Feriado'), ('S_A', 'Suspension de actividades'), ('S_A_PM', 'Suspension de actividades (PM)'), ('P', 'Periodo Lectivo'), ('S_E', 'Suspension de evaluaciones'), ('C', 'Ceremonia'), ('E', 'EDDA'), ('A', 'Ayudantias'), ('H', 'Hito Academico'), ('S', 'Secretaria Academica'), ('Q', 'QAI')], max_length=30),
        ),
    ]
